theme: jekyll-theme-architect
github:
  zip_url: https://github.com/novayo/NCKU_COMPUTER_PROJECT_DESIGN/archive/master.zip
  tar_url: https://github.com/novayo/NCKU_COMPUTER_PROJECT_DESIGN/archive/master.tar.gz
